### ISSUE TITLE
(UI/UX) Website Design & Implementation

### ISSUE THREAD

**Issue by TFPlusPlus** [UoaWDCC/uasc-web#1]
### User story:

As a visitor,
I want to navigate through different parts of the website using a navigation bar, with every part outlining different aspects of the club,
So that I can understand more about the club, such as event information, membership prices, and pictures.

### Acceptance Criteria (Provisional):
- [ ] Functional navigation bar
- [ ] Various pages in place for deploying components (Home, Events Information, FAQ, Sign-up, etc)
- [ ] Pleasant user experience (user-friendly, intuitive)

### Definition of Done:
- [ ] AC met
- [ ] Applicable tests written
- [ ] Applicable documentation is written in GH wiki
- [ ] PR reviewed
- [ ] Merged into main/feature branch

### Notes / Links
UI/UX Task

**Comment by selinakkaya** [comment]
Complete under uasc-1/nav-bars
