### ISSUE TITLE
[BACKEND] [WEBHOOK] Add logic for setting a member's role on successful checkout

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#132]
**WARNING**: HARD

**Is your feature request related to a problem? Please describe.**
Blocked by #131 

After a member pays for membership, the webhook will be hit by a ~~[checkout.session.completed](https://docs.stripe.com/api/events/types#event_types-checkout.session.completed), and we need to handle this.~~ [payment_intent.succeeded](https://docs.stripe.com/api/events/types#event_types-payment_intent.succeeded)

**Describe the solution you'd like**
- Retrieve the relevant checkout session using #237 
- Need to check the `client_reference_id` (which will give the user's firebase uid)
- Check metadata for the appropriate key (to check that the payment was for club membership)
- ~~Add their customer id to the firestore using `UserService` blocked by #239 (can do in same branch)~~ WONT do because emails are unique in firebase so we dont need another identifier
- Update firestore 
- Add member claim to user

**Additional context**
Any business logic failures should not give a `200` response

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by jeffplays2005** [comment]
- [ ] Need to check the client_reference_id (which will give the user's firebase uid)

- [ ] Check metadata for the appropriate key (to check that the payment was for club membership)

- [ ] Update firestore

- [ ] Add member claim to user
