### ISSUE TITLE
[BACKEND] Paginate all bookings endpoint

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by 8cw** [comment]
Closed in favor of #138
