### ISSUE TITLE
[BACKEND] [WEBHOOK] Update booking_slot in firestore when its active status changes

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#153]
**Is your feature request related to a problem? Please describe.**
If a product is set as inactive then it should be reflected on the frontend, therefore we need to change its status in firestore too 

**Describe the solution you'd like**
when the [price.updated](https://docs.stripe.com/api/events/types#event_types-price.updated) is hit, and the meta data suggests it is a booking slot, we need to find the matching document and update its status.

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by 8cw** [comment]
I'm wondering if we should just use Stripe as the source of truth for the price of products. It would probably make it a lot easier for us to make sure the state is synchronized.

Doing so _would_ require us to have the http endpoint to retrieve the product information from Stripe, but I think it would simplify our architecture a lot more.

**Comment by bcho892** [comment]
> I'm wondering if we should just use Stripe as the source of truth for the price of products. It would probably make it a lot easier for us to make sure the state is synchronized.
> 
> Doing so _would_ require us to have the http endpoint to retrieve the product information from Stripe, but I think it would simplify our architecture a lot more.

We would have to find a good way to use metadata, but yes I would prefer this solution

**Comment by 8cw** [comment]
Closed in favor of new architecture.
