### ISSUE TITLE
[FRONTEND] Make banner on homepage responsive

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#286]
**Is your feature request related to a problem? Please describe.**

![Image](https://github.com/UoaWDCC/uasc-web/assets/100653148/3e214183-3daf-484c-aaa4-1a6fa68eb096)

Assume mobile is < sm breakpoint
i.e
```
<div class="sm:text-center">
  This text will be centered on medium screens, but revert back
  to the default (left-aligned) at all other screen sizes.
</div>
```

**BEFORE MERGING**

- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by jeffplays2005** [comment]
Is the same already.
