### ISSUE TITLE
[FRONTEND] Display bookings a user has

### ISSUE THREAD

**Issue by 8cw** [UoaWDCC/uasc-web#292]
**Is your feature request related to a problem? Please describe.**
The user needs a way to view the bookings they have. This lets them know what dates they have, as well as provides the framework for letting them cancel a booking and edit their booking.

You should display this on the profile page created in #360 using the table made in #369 . For examples of how to use the table, check out the work in #163 and #390 

It is required also have no overflow issues on the profile page

Ignore the "Request Cancellation", "no. beds" button - just display all the individual dates

![Image](https://github.com/UoaWDCC/uasc-web/assets/100653148/7e44910c-fcfe-45ae-b797-101b2fd04d0d)

**Describe the solution you'd like**
A query hook needs to be created that calls the endpoint made in #338 

We need a frontend page where the user can view all bookings they currently have in the future. We may also want to display past bookings a user had (not sure on this, needs client consultation if this is necessary).

**Additional context**
See #140 and #139 which will develop from this ticket, once the user views the bookings they have.

**BEFORE MERGING**
- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by bcho892** [comment]
completed in #553
