### ISSUE TITLE
[BACKEND] Handle failed Stripe booking payments

### ISSUE THREAD

**Issue by 8cw** [UoaWDCC/uasc-web#293]
**Is your feature request related to a problem? Please describe.**
note: this issue is in a WIP state. other features related to hut booking must be done before we figure out if this is necessary.

Implementation in #133 specifies that a `checkout.session.completed` is good enough to reserve a bed. However, the user may not have quite fully paid by now (e.g., an asynchronous payment method).
If this is the case (that it is possible for us to have a `checkout.session.completed` followed by a `checkout.session.async_payment_failed`), we need to handle failed payments once a hut has been reserved and remove the booking from the user.

**Describe the solution you'd like**
Investigate if we have async payment methods, and if such a scenario is possible. If it is, then implement the logic described above. Otherwise, close this issue.

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] [Schemas annotated](https://tsoa-community.github.io/docs/annotations.html) if adding new models
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by bcho892** [comment]
not needed as NZ does not support async payment methods
