### ISSUE TITLE
[FRONTEND] Update the pricing banner on homepage to say $60 for single friday/saturday

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#451]
**Is your feature request related to a problem? Please describe.**

This thing:

![Image](https://github.com/UoaWDCC/uasc-web/assets/100653148/3447422c-6fd0-4076-8cd2-b00f309a3077)

**BEFORE MERGING**

- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by bcho892** [comment]
![Screenshot_20240620-191543](https://github.com/UoaWDCC/uasc-web/assets/100653148/9a04a62b-3975-4c9c-9681-f873f94971a1)

**Comment by zlrkw11** [comment]
![image](https://github.com/UoaWDCC/uasc-web/assets/64724157/72212251-3fed-4ab4-b4cd-f276c63e5b27)
fixed
