### ISSUE TITLE
[BACKEND] Create data structure for managing Event details

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#591]
**Is your feature request related to a problem? Please describe.**

Will need to have a look at the work being done in #345. Make sure you define and **document** them in `server\src\data-layer\models\firebase.ts`. The wiki at https://github.com/UoaWDCC/uasc-web/wiki/Firestore-Architecture also needs to be updated

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] [Schemas annotated](https://tsoa-community.github.io/docs/annotations.html) if adding new models
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by jeffplays2005** [comment]
<img width="969" alt="Screenshot 2024-07-27 at 12 03 15 AM" src="https://github.com/user-attachments/assets/263b5dee-2b73-4b32-bc7b-34c046ab84b4">

Event slot collection has been documented
