### ISSUE TITLE
[FRONTEND] Validate input fields on sign up

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#611]
**Is your feature request related to a problem? Please describe.**
You will have to validate the fields in `uasc-next\src\store\SignUpForm.tsx` 

- `dietary_requirements`
- `emergency_contact`

**BEFORE MERGING**

- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by jeffplays2005** [comment]
Gonna edit the title to Signup validation or something as there are quite a couple fields that probably would be better with validation and some that are optional.
