### ISSUE TITLE
[FRONTEND] Write custom hook to recieve SSE (Server Sent Events)

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#778]
**Is your feature request related to a problem? Please describe.**

Because of the new endpoint created in #662 we will now need to have a way to consume the events on the frontend. For our project this will consist of two steps:

1. Create a generic hook that allows creation of an [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) for a given endpoint and appropriately attach callbacks or if a request body is required a library such as [`fetchEventSource`](https://github.com/Azure/fetch-event-source) would be required
2. Use that implementation to create a hook that allows us to constantly stream event signup numbers on the front end

>[!NOTE]
>You should not be hard-coding the base url for the endpoint, instead look into `process.env` to get the appropriate base URL

>[!WARNING]
>There should be a way for us to close the connection if needed

**BEFORE MERGING**

- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by jeffplays2005** [comment]
Not planned
